version: "3.7"

services:
  localstack:
    image: localstack/localstack:0.10.5
    ports:
      - 4572:4572
      - 4576:4576
      - 8081:8080
    environment:
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - SERVICES=s3:4572,sqs
      - DEFAULT_REGION=eu-west-1
